# Generated by Django 4.2.3 on 2023-07-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_comment_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
