# Generated by Django 4.2.3 on 2023-07-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_approved"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterField(
            model_name="post",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
